package com.bithumbsystems.auth.model.lrc.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum ErrorCode {
  UNKNOWN_ERROR("F001", "UNKNOWN_ERROR"),

  INVALID_FILE("F002","INVALID_FILE"),
  FAIL_SAVE_FILE("F003","FAIL_SAVE_FILE"),
  NOT_FOUND_CONTENT("F004","NOT_FOUND_CONTENT"),
  FAIL_UPDATE_CONTENT("F005","FAIL_UPDATE_CONTENT"),
  FAIL_CREATE_CONTENT("F006","FAIL_CREATE_CONTENT"),
  FAIL_REQUEST_VALIDATE("F007","FAIL_REQUEST_VALIDATE"),
  INVALID_TOKEN("F008","INVALID_TOKEN"),

  DUPLICATE_DATA("F009", "DUPLICATE_DATA"),
  FAIL_SEND_MAIL("M411","FAIL_SEND_MAIL"),
  FAIL_JOIN_EMAIL_VALID("F010","FAIL_JOIN_EMAIL_VALID"),
  FAIL_JOIN_EMAIL_VALID_EXPIRE("F011","FAIL_JOIN_EMAIL_VALID_EXPIRE"),
  FAIL_PASSWORD_EMAIL_NOTFOUND("F012","FAIL_PASSWORD_EMAIL_NOTFOUND"),
  FAIL_PASSWORD_EMAIL_VALID("F013","FAIL_PASSWORD_EMAIL_VALID"),
  FAIL_PASSWORD_RESET("F014","FAIL_PASSWORD_RESET"),
  FAIL_PASSWORD_RESET_EXPIRE("F015","FAIL_PASSWORD_RESET_EXPIRE"),
  INVALID_MAX_FILE_SIZE("F016","INVALID_MAX_FILE_SIZE"),
  INVALID_FILE_EXT("F017","INVALID_FILE_EXT"),
  NO_PROJECT_USER("F018","NO_PROJECT_USER"),
  NOT_FOUND_PROJECT("F019","NOT_FOUND_PROJECT"),
  FAIL_PASSWORD_PREV("F020","FAIL_PASSWORD_PREV"),
  ALREADY_EMAIL_VALID("F021","ALREADY_EMAIL_VALID"),
  INVALID_PASSWORD("F022","INVALID_PASSWORD"),
  LIMIT_RETRY_JOIN_EMAIL("F023","LIMIT_RETRY_JOIN_EMAIL"),
  NO_PERMISSION("F024","NO_PERMISSION");

  private final String code;

  private final String message;
}
