version: '3'
services:
  redis:
    image: redis:6.2
    container_name: dev-redis
    ports:
      - "6379:6379"
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf