apiVersion: apps/v1
kind: Deployment
metadata:
  name: systems-auth-api
  namespace: #NAMESPACE#
  labels:
    app: systems-auth-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: systems-auth-api
  strategy: {}
  template:
    metadata:
      labels:
        app: systems-auth-api
    spec:
      containers:
        - name: systems-auth-api
          image: #AWS_ECR_URI#
          ports:
            - containerPort: 8080
          resources: {}