server:
  shutdown: graceful
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: false
  data:
    mongodb:
      auto-index-creation: true
      uuid-representation: standard
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
  redis:
    timeout: 60000
  pid:
    file: ${instance.pid}

management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus, health
  health:
    redis:
      enabled: false

logging:
  level:
    root: ${auth.api.logging.level.root:DEBUG}
    org.springframework.data.convert.CustomConversions: ERROR
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: ${auth.api.logging.level.mongo:DEBUG}
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        encryptionsdk: DEBUG

    io:
      spring:
        cloud: INFO

bithumbsystems:
  auth:
    public-routes: /api/v1/**,/webjars/**,/actuator/**,/pingpong/**,/webjars/swagger-ui/**,/favicon.ico,/swagger-ui.html,/api-docs/**

google:
  recaptcha:
    verify:
      url: https://www.google.com/recaptcha/api/siteverify
    secret:
      lrc: 6Lef7JcfAAAAAKFN2Wta__cXutJ4wCMeCadxl3Eq
---
spring:
  config:
    import: classpath:aws-properties.yml, classpath:springdoc.yml
    activate:
      on-profile: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  redis:
    host: ${auth.redis.host:localhost}
    port: ${auth.redis.port:6379}
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
mail:
  logo-url: http://k8s-systemsd-systemsm-5b1ad0cbb7-1915523199.ap-northeast-2.elb.amazonaws.com/images/maillogo.png
  login-url: http://localhost:3000/
---
spring:
  config:
    import: classpath:aws-properties-dev.yml, classpath:springdoc.yml
    activate:
      on-profile: dev
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
mail:
  logo-url: http://k8s-systemsd-systemsm-5b1ad0cbb7-1915523199.ap-northeast-2.elb.amazonaws.com/images/maillogo.png
  login-url: http://k8s-systemsd-systemsm-5b1ad0cbb7-1915523199.ap-northeast-2.elb.amazonaws.com
---
spring:
  config:
    import: classpath:aws-properties-eks-dev.yml, classpath:springdoc.yml
    activate:
      on-profile: eks-dev
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
mail:
  logo-url: http://k8s-systemsd-systemsm-5b1ad0cbb7-1915523199.ap-northeast-2.elb.amazonaws.com/images/maillogo.png
  login-url: http://k8s-systemsd-systemsm-5b1ad0cbb7-1915523199.ap-northeast-2.elb.amazonaws.com
---
spring:
  config:
    import: classpath:aws-properties-qa.yml, classpath:springdoc.yml
    activate:
      on-profile: qa
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
mail:
  logo-url: http://k8s-systemsd-systemsm-5b1ad0cbb7-1915523199.ap-northeast-2.elb.amazonaws.com/images/maillogo.png
  login-url: http://k8s-systemsd-systemsm-5b1ad0cbb7-1915523199.ap-northeast-2.elb.amazonaws.com
---
spring:
  config:
    import: classpath:aws-properties.yml
    activate:
      on-profile: prod
springdoc:
  api-docs:
    enabled: false
mail:
  logo-url: https://smartadmin.bithumb.com/images/maillogo.png
  login-url: https://smartadmin.bithumb.com
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml