server:
  shutdown: graceful
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus, health

logging:
  level:
    root: ${auth.api.logging.level.root:DEBUG}
    org.springframework.data.convert.CustomConversions: ERROR
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: ${auth.api.logging.level.mongo:DEBUG}
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        encryptionsdk: DEBUG

    io:
      spring:
        cloud: INFO

bithumbsystems:
  auth:
    public-routes: /api/v1/**,/webjars/**,/actuator/**,/webjars/swagger-ui/**,/favicon.ico,/swagger-ui.html,/api-docs/**
    jwt:
      secret: ${auth.api.jwt.secret:eyJzdWIiOiJtaW5zb3ViQGJpdGh1bWJzeXN0ZW1zLmNvbSIsIm5hbWUiOiJCaXRodW1iU3lzdGVtcyIsImlhdCI6MjA5OTEyMzExMjF9.Lpo86rOQtvBRfVKDGhICUWuZ92rgBIVPM9PVAUiRhAM}
      expiration:
        access: ${auth.api.jwt.expiration.access:28800}
        refresh: ${auth.api.jwt.expiration.refresh:28800}


---
spring:
  config:
    import: classpath:aws-properties.yml, classpath:springdoc.yml
    activate:
      on-profile: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  redis:
    host: ${auth.redis.host:localhost}
    port: ${auth.redis.port:6379}
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
---
spring:
  config:
    import: classpath:aws-properties-dev.yml, classpath:springdoc.yml
    activate:
      on-profile: dev
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
---
spring:
  config:
    import: classpath:aws-properties-dev.yml, classpath:springdoc.yml
    activate:
      on-profile: eks-dev
logging:
  config: classpath:logback-spring-dev.xml
---
spring:
  config:
    import: classpath:aws-properties.yml
    activate:
      on-profile: prod
springdoc:
  api-docs:
    enabled: false
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml